#### Need of array =>

#### interview questions

1. 2d
2. contain homogeneous data type
3. Perform mathematical operations due to same data type


In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.23.5


In [4]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
mularr=np.array([[1,2,3,4],[1,2,3,4]])
mularr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [6]:
d=np.zeros(6)
d

array([0., 0., 0., 0., 0., 0.])

In [8]:
d=np.zeros((6,5)) # double brackets multidimensional
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
d=np.zeros((2,3,4))
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])