In [1]:
#1. Keras = Machine learning/Data mining(regression,clustering,etc)
#2. Matplotlib = Desigining charts,graphs,picharts,scatter plots,histogram,etc
#3. Numpy = Array representation (assoiciated with various libraries internally)
#4. NLTK = Natural language processing
#5. OpenCV = Open source computer vision library (Specially for Image processing)
#6. Pandas = Data analaysis (Features- Re-indexing, sorting, Iterative, concatination,etc.)
#7. PyTorch = Machine learning/ Deep learning
#8. Scikit Learn =  Machine Learning
#9. SciPy = Scientific Python( Statistics, Algebra, Integration math related functions)
#10. Seaborn = Data Visualization library( High level interactive and informative pacakage)
#11. Tensor Flow = Machine Learning Library( To compute tensor operations i.e. represent data in n-dimension matrices)

In [2]:
import numpy as np
import pandas as pd

In [3]:
a=[1,2,3,4]
b=np.asarray(a)
print(b)

[1 2 3 4]


In [4]:
type(b)

numpy.ndarray

In [5]:
c=(1,2,3,4)
d=np.asarray(a)
print(d)

[1 2 3 4]


In [6]:
type(d)

numpy.ndarray

In [7]:
a+d

array([2, 4, 6, 8])

### arange(),linspace(),logspace()

In [8]:
#start , stop,step, dtype
np.arange(0,10,2,dtype=float)

array([0., 2., 4., 6., 8.])

In [9]:
np.arange(0,55,5,dtype=float)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [13]:
np.eye(3 , dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [14]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)

In [15]:
np.add(a,b)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [16]:
np.subtract(a,b)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [17]:
np.multiply(a,b)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [18]:
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]))

In [19]:
np.divide(a,b)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [20]:
np.power(a,b)

array([[          1,        4096,     1594323],
       [  268435456,   452807053,  -683606016],
       [-2094633337,           0,  -400556711]])

In [21]:
np.mod(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Pandas

In [22]:
import numpy as np
import pandas as pd

In [23]:
l=[1,2,3,7]
pd.Series(l)

0    1
1    2
2    3
3    7
dtype: int64

In [24]:
pd.Series(l,index=["a","b","c","d"])

a    1
b    2
c    3
d    7
dtype: int64

In [25]:
a=pd.Series()
a

C:\Users\Anuja\AppData\Local\Temp\ipykernel_10968\454184989.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  a=pd.Series()


Series([], dtype: float64)

In [26]:
a=np.array([11,12,13])
a1=pd.Series(a)
a1

0    11
1    12
2    13
dtype: int32

In [27]:
d={"a":10,"b":11,"c":12,"d":13}
d

{'a': 10, 'b': 11, 'c': 12, 'd': 13}

In [28]:
a1=pd.Series(d)
a1

a    10
b    11
c    12
d    13
dtype: int64

In [29]:
type(a1)

pandas.core.series.Series

## DataFrame

In [30]:
#C:\Users\Anuja\Music\New folder\sample 1.xls

In [31]:
data=pd.read_excel(r"C:\Users\Anuja\Music\New folder\sample 1.xls")
data.head()

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

In [32]:
data=pd.read_csv(r"C:\Users\Anuja\Music\New folder\Credit_Risk_data.csv")
data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [33]:
data.shape

(614, 13)

In [34]:
data.Gender.head()

0    Male
1    Male
2    Male
3    Male
4    Male
Name: Gender, dtype: object

In [35]:
data["Gender"].head()

0    Male
1    Male
2    Male
3    Male
4    Male
Name: Gender, dtype: object

In [36]:
data.ApplicantIncome.head().mean()

4403.0

In [37]:
data.ApplicantIncome.mean()

5403.459283387622

In [38]:
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [39]:
newdf=data[data.ApplicantIncome > 4000] # filtering to whole dataset

In [40]:
newdf.shape

(280, 13)

In [41]:
data.shape

(614, 13)

In [42]:
female=data[(data.Gender == "Female")&(data.Education == "Graduate")&(data.Married =="Yes")&(data.ApplicantIncome > 2000)] 

In [43]:
female.shape

(24, 13)

In [44]:
(2**3)**2

64

In [45]:
df=data

In [46]:
df.groupby("Gender").ApplicantIncome.mean()

Gender
Female    4643.473214
Male      5446.460123
Name: ApplicantIncome, dtype: float64

In [47]:
df.columns.to_list()

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [48]:
df.groupby("Married").ApplicantIncome.mean()

Married
No     4970.384977
Yes    5629.173367
Name: ApplicantIncome, dtype: float64

In [49]:
df.groupby("Gender").agg(["count","min","max","mean","median"])

C:\Users\Anuja\AppData\Local\Temp\ipykernel_10968\4001268329.py:1: FutureWarning: ['Loan_ID', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby("Gender").agg(["count","min","max","mean","median"])


ApplicantIncome                                  CoapplicantIncome  \
                 count  min    max         mean  median             count   
Gender                                                                      
Female             112  210  19484  4643.473214  3583.0               112   
Male               489  150  81000  5446.460123  3865.0               489   

                                           ... Loan_Amount_Term               \
        min      max         mean  median  ...            count   min    max   
Gender                                     ...                                 
Female  0.0  41667.0  1108.008929     0.0  ...              109  36.0  480.0   
Male    0.0  33837.0  1742.932352  1430.0  ...              478  12.0  480.0   

                          Credit_History                             
              mean median          count  min  max      mean median  
Gender                                                               
Female  352.293578  360.0            101  0.0  1.0  0.831683    1.0  
Male    339.665272  360.0            451  0.0  1.0  0.847007    1.0  

[2 rows x 25 columns]

In [50]:
pd.crosstab(df.Gender,df.Loan_Status)

Loan_Status    N    Y
Gender               
Female        37   75
Male         150  339

In [51]:
pd.crosstab(df.Self_Employed,df.Loan_Status)

Loan_Status      N    Y
Self_Employed          
No             157  343
Yes             26   56

In [52]:
df1=df.drop(["Loan_ID"] , axis=1)

In [53]:
df1.head(2)

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
0   Male      No          0  Graduate            No             5849   
1   Male     Yes          1  Graduate            No             4583   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N

In [54]:
df1.shape

(614, 12)

## cleaning data (preprocessing)

In [55]:
#df1.describe(include=all)

In [56]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             601 non-null    object 
 1   Married            611 non-null    object 
 2   Dependents         599 non-null    object 
 3   Education          614 non-null    object 
 4   Self_Employed      582 non-null    object 
 5   ApplicantIncome    614 non-null    int64  
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object 
 11  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB


#### df.dropna()  => to delete null values

In [57]:
df1.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [58]:
df1.Gender=df.Gender.fillna("Female") 

In [59]:
df1.Gender.count()

614

In [60]:
df1['Married'].value_counts()

Yes    398
No     213
Name: Married, dtype: int64

In [61]:
df1.Married=df1.Married.fillna("No")

In [62]:
df1['Married'].value_counts()

Yes    398
No     216
Name: Married, dtype: int64

In [63]:
df1['Self_Employed'].value_counts()

No     500
Yes     82
Name: Self_Employed, dtype: int64

In [64]:
df1.Self_Employed=df1.Self_Employed.fillna("Yes")

In [65]:
df1['Self_Employed'].value_counts()

No     500
Yes    114
Name: Self_Employed, dtype: int64

In [66]:
df1.dtypes

Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [67]:
df1.Dependents=df1.Dependents.fillna("3+")

In [68]:
df1.Dependents.value_counts()

0     345
1     102
2     101
3+     66
Name: Dependents, dtype: int64

In [69]:
df1.LoanAmount=df1.LoanAmount.fillna(df1.LoanAmount.mean())

In [70]:
df1.Loan_Amount_Term=df1.Loan_Amount_Term.fillna(df1.Loan_Amount_Term.median())

In [71]:
df1.Credit_History=df1.Credit_History.fillna(0.0)

In [72]:
df1.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

## Data type conversion

### using replace method

In [73]:
#d["three"]=d["three"].astype("int")

In [74]:
#df1.Gender.value_counts()

In [75]:
#df1.Married.replace({"Female":0,"Male":1},inplace=True)

In [76]:
#df1.head()

In [77]:
#df1.Married.value_counts()

In [78]:
#df1.Married.replace({"Yes":0,"No":1},inplace=True)

In [79]:
#df1.Education.value_counts()

In [80]:
#df1.Education.replace({"Graduate":0,"Not Graduate":1},inplace=True)

In [81]:
#df1.Self_Employed.value_counts()

In [82]:
#df1.Self_Employed.replace({"No":0,"Yes":1},inplace=True)

In [83]:
#df1.Loan_Status.value_counts()

In [84]:
#df1.Loan_Status.replace({"Y":0,"N":1},inplace=True)

In [85]:
#df1.head(5)

In [86]:
#df1.Dependents.replace({"0":0,"1":1,"2":2,"3":3},inplace=True)

In [87]:
#df1.Property_Area.value_counts()

In [88]:
#df1.Property_Area.replace({"Semiurban":0,"Urban":1,"Rural":2},inplace=True)

In [89]:
#df1.dtypes

In [90]:
df1=pd.get_dummies(df1,columns=["Gender","Married","Dependents","Education","Self_Employed","Property_Area","Loan_Status"])

In [91]:
df1.dtypes

ApplicantIncome              int64
CoapplicantIncome          float64
LoanAmount                 float64
Loan_Amount_Term           float64
Credit_History             float64
Gender_Female                uint8
Gender_Male                  uint8
Married_No                   uint8
Married_Yes                  uint8
Dependents_0                 uint8
Dependents_1                 uint8
Dependents_2                 uint8
Dependents_3+                uint8
Education_Graduate           uint8
Education_Not Graduate       uint8
Self_Employed_No             uint8
Self_Employed_Yes            uint8
Property_Area_Rural          uint8
Property_Area_Semiurban      uint8
Property_Area_Urban          uint8
Loan_Status_N                uint8
Loan_Status_Y                uint8
dtype: object

In [92]:
df1.shape

(614, 22)

In [93]:
df1

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History  Gender_Female  Gender_Male  Married_No  Married_Yes  \
0               1.0              0            1           1            0   
1               1.0              0            1           0            1   
2               1.0              0            1           0            1   
3               1.0              0            1           0            1   
4               1.0              0            1           1            0   
..              ...            ...          ...         ...          ...   
609             1.0              1            0           1            0   
610             1.0              0            1           0            1   
611             1.0              0            1           0            1   
612             1.0              0            1           0            1   
613             0.0              1            0           1            0   

     Dependents_0  ...  Dependents_3+  Education_Graduate  \
0               1  ...              0                   1   
1               0  ...              0                   1   
2               1  ...              0                   1   
3               1  ...              0                   0   
4               1  ...              0                   1   
..            ...  ...            ...                 ...   
609             1  ...              0                   1   
610             0  ...              1                   1   
611             0  ...              0                   1   
612             0  ...              0                   1   
613             1  ...              0                   1   

     Education_Not Graduate  Self_Employed_No  Self_Employed_Yes  \
0                         0                 1                  0   
1                         0                 1                  0   
2                         0                 0                  1   
3                         1                 1                  0   
4                         0                 1                  0   
..                      ...               ...                ...   
609                       0                 1                  0   
610                       0                 1                  0   
611                       0                 1                  0   
612                       0                 1                  0   
613                       0                 0                  1   

     Property_Area_Rural  Property_Area_Semiurban  Property_Area_Urban  \
0                      0                        0                    1   
1                      1                        0                    0   
2                      0                        0                    1   
3                      0                        0                    1   
4                      0                        0                    1   
..                   ...                      ...                  ...   
609                    1                        0                    0   
610                    1                        0                    0   

### types of null values

In [94]:
dirty=pd.read_csv(r'C:\Users\Anuja\Downloads\dirtydata.csv')

In [95]:
dirty.shape

(32, 5)

In [96]:
dirty.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [97]:
dirty.Calories=dirty.Calories.fillna(dirty.Calories.median())

In [98]:
dirty.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [99]:
dirty.dropna(inplace=True)

In [100]:
dirty.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [101]:
dirty

Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     291.2
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     291.2
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [102]:
dirty.loc[7,"Duration"]=45

In [103]:
dirty

Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     291.2
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     291.2
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [104]:
dirty.drop_duplicates(inplace=True)

In [105]:
dirty.shape

(30, 5)

In [106]:
df12=pd.read_csv(r'C:\Users\Anuja\Downloads\train_Hr.csv')

In [107]:
df12.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [108]:
df12.drop('education', axis=1, inplace=True)

In [109]:
df12.drop('previous_year_rating', axis=1, inplace=True)

In [110]:
df12.isnull().sum()

employee_id            0
department             0
region                 0
gender                 0
recruitment_channel    0
no_of_trainings        0
age                    0
length_of_service      0
KPIs_met >80%          0
awards_won?            0
avg_training_score     0
is_promoted            0
dtype: int64

In [111]:
df12.head(2)

employee_id         department     region gender recruitment_channel  \
0        65438  Sales & Marketing   region_7      f            sourcing   
1        65141         Operations  region_22      m               other   

   no_of_trainings  age  length_of_service  KPIs_met >80%  awards_won?  \
0                1   35                  8              1            0   
1                1   30                  4              0            0   

   avg_training_score  is_promoted  
0                  49            0  
1                  60            0