In [1]:
#1. Keras = Machine learning/Data mining(regression,clustering,etc)
#2. Matplotlib = Desigining charts,graphs,picharts,scatter plots,histogram,etc
#3. Numpy = Array representation (assoiciated with various libraries internally)
#4. NLTK = Natural language processing
#5. OpenCV = Open source computer vision library (Specially for Image processing)
#6. Pandas = Data analaysis (Features- Re-indexing, sorting, Iterative, concatination,etc.)
#7. PyTorch = Machine learning/ Deep learning
#8. Scikit Learn =  Machine Learning
#9. SciPy = Scientific Python( Statistics, Algebra, Integration math related functions)
#10. Seaborn = Data Visualization library( High level interactive and informative pacakage)
#11. Tensor Flow = Machine Learning Library( To compute tensor operations i.e. represent data in n-dimension matrices)

In [2]:
import numpy as np

In [13]:
a=[1,2,3,4]
b=np.asarray(a)
print(b)

[1 2 3 4]


In [14]:
type(b)

numpy.ndarray

In [15]:
c=(1,2,3,4)
d=np.asarray(a)
print(d)

[1 2 3 4]


In [16]:
type(d)

numpy.ndarray

In [18]:
a+d

array([2, 4, 6, 8])

### arange(),linspace(),logspace()

In [23]:
#start , stop,step, dtype
np.arange(0,10,2,dtype=float)

array([0., 2., 4., 6., 8.])

In [25]:
np.arange(0,55,5,dtype=float)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [26]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [29]:
np.eye(3 , stype="int")

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)

In [31]:
np.add(a,b)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [32]:
np.subtract(a,b)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [33]:
np.multiply(a,b)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [34]:
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]))

In [35]:
np.divide(a,b)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [36]:
np.power(a,b)

array([[          1,        4096,     1594323],
       [  268435456,   452807053,  -683606016],
       [-2094633337,           0,  -400556711]])

In [37]:
np.mod(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Pandas

In [8]:
import numpy as np
import pandas as pd

In [3]:
l=[1,2,3,7]
pd.Series(l)

0    1
1    2
2    3
3    7
dtype: int64

In [4]:
pd.Series(l,index=["a","b","c","d"])

a    1
b    2
c    3
d    7
dtype: int64

In [6]:
a=pd.Series()
a

C:\Users\Anuja\AppData\Local\Temp\ipykernel_6644\454184989.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  a=pd.Series()


Series([], dtype: float64)

In [10]:
a=np.array([11,12,13])
a1=pd.Series(a)
a1

0    11
1    12
2    13
dtype: int32

In [11]:
d={"a":10,"b":11,"c":12,"d":13}
d

{'a': 10, 'b': 11, 'c': 12, 'd': 13}

In [12]:
a1=pd.Series(d)
a1

a    10
b    11
c    12
d    13
dtype: int64

In [13]:
type(a1)

pandas.core.series.Series