#### Need of array =>

#### interview questions

1. 2d
2. contain homogeneous data type
3. Perform mathematical operations due to same data type


In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.23.5


# Array creation

In [4]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
mularr=np.array([[1,2,3,4],[1,2,3,4]])
mularr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [6]:
d=np.zeros(6)
d

array([0., 0., 0., 0., 0., 0.])

In [8]:
d=np.zeros((6,5)) # double brackets multidimensional
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
d=np.zeros((2,3,4))
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
x=np.random.randn(2,3)
x 

array([[-0.26135708, -0.11310377,  0.66990216],
       [ 0.87351848,  0.16143284, -0.12897176]])

In [8]:
x=np.random.randn(2,3,2)
x

array([[[-0.93000982, -1.07961962],
        [-0.18487476, -0.39222061],
        [ 0.83430055,  0.12743745]],

       [[-0.01433313,  1.34934061],
        [ 0.56282362, -2.07067134],
        [ 0.26364006, -0.04724256]]])

###### numpy.empty(shape, dtype=float, order='C', *, like=None)

In [29]:
x=np.empty(6) 
x

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.86921143e-306,
       1.89146896e-307, 7.56571288e-307])

In [14]:
x=np.empty((2,3)) # (2,3) <= this is not working , single braces not working
x

array([[0.26135708, 0.11310377, 0.66990216],
       [0.87351848, 0.16143284, 0.12897176]])

In [15]:
y=np.empty((2,3,2)) # (2,3) <= this is not working , single braces not working
y

array([[[0.93000982, 1.07961962],
        [0.18487476, 0.39222061],
        [0.83430055, 0.12743745]],

       [[0.01433313, 1.34934061],
        [0.56282362, 2.07067134],
        [0.26364006, 0.04724256]]])

###### numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

N :int
Number of rows in the output.

M :int, optional
Number of columns in the output. If None, defaults to N.

k : int, optional
Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

In [34]:
arr=np.eye(3, k=1, dtype=int)
arr1 = np.eye(2,3)
print(arr )
print(arr1)# refers to the main diagonal,

[[0 1 0]
 [0 0 1]
 [0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]]


In [16]:
z=np.arange(15)  # 1 D
z 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
p=np.arange(12).reshape(3,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
q=np.arange(8).reshape(2,2,2)
q

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
r=np.asarray([[1,2,3],[4,5,6],[7,8,9]])
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
r=np.ones((3,4) , dtype=int)  
r


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
s=np.ones((2,2,2))
s

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [44]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a[1,:]

array([4, 5, 6])

In [46]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [22]:
print(a[1,2],"this is for row col-", a[0,:], a[:,0], a[0:2,0:2], a[1,:2],sep="---")

6---this is for row col----[1 2 3]---[1 4 7]---[[1 2]
 [4 5]]---[4 5]


In [21]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [26]:
a[:,2]

array([3, 6, 9])

In [27]:
a[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### [8, 9] for this type directly write(row no , then write columns in ratio)

In [32]:
#op - 89 
a[2,1:]

array([8, 9])

In [33]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [8]:
a=np.array(30)
a.ndim # 0 dimension

0

In [10]:
a=np.array((30,40))
a.ndim

1

In [11]:
a=np.array([  [1,2,3],[4,5,6],[7,8,9] ])
a.ndim

2

In [2]:
arr4=np.array([[  [11,22,33],[44,55,66],[40,50,60] ]])
arr4.ndim

3

In [17]:
arr4=np.array([[  [[[[[[[[1,2,3]]]]]]]] ]])
arr4.ndim

10

In [18]:
arr4=np.array([1,2,3] , ndmin=3) # creating of particular dimension
arr4.ndim

3

In [39]:
z=np.array([ 
             [ [11,22,33],
               [44,55,66]  ],
 
             [ [77,88,99],
               ["qq","ww","ee"]  ],
            ])
z.ndim

3

In [12]:
arr4

array([[[11, 22, 33],
        [44, 55, 66],
        [40, 50, 60]]])

##### fetching particular elements from 1D pass index positions in  [[     ]]

In [14]:
a=np.array([11,12,13,14,15,16,17,18,19])
a[[0,6,3]] 

array([11, 17, 14])

In [40]:
z[1,1,1]

'ww'

In [41]:
z[0,1,2]

'66'

In [43]:
#55,66
z[0,1,1:]

array(['55', '66'], dtype='<U11')

In [24]:
import numpy as np
z=np.array([ 
             [ [11,22,33],
               [44,55,66]  ],
 
             [ [77,88,99],
               [12,13,14]  ],
            ])

In [5]:
z[1,0:,:2]

array([[77, 88],
       [12, 13]])

In [4]:
z[0,0:,1:]

array([[22, 33],
       [55, 66]])

In [26]:
z[(0,1),(1,0),1:]

array([[55, 66],
       [88, 99]])

In [25]:
#find slicing for 55,66 88,99

In [6]:
star=np.array(["apple","banana","cherry"])
star.dtype

dtype('<U6')

In [7]:
star=np.array(["apple","bananaaaaaaaaaaa","cherry"])
star.dtype # U16 cause highest string is og len 16

dtype('<U16')

In [9]:
a=np.array([1,2,3] , dtype="i4")
a

array([1, 2, 3])

In [10]:
a=np.array([1,2,3] , dtype="S")
a

array([b'1', b'2', b'3'], dtype='|S1')

In [12]:
a=np.array([1,2,3,"anuja"],dtype="S")
a

array([b'1', b'2', b'3', b'anuja'], dtype='|S5')

In [13]:
b=np.array([1.2,1.3,1.4])
b.astype('i') # astype used to convert data 

array([1, 1, 1], dtype=int32)

In [14]:
import copy
# original = b

In [16]:
x1=b.copy()

In [17]:
x2=b.deepcopy()

AttributeError: 'numpy.ndarray' object has no attribute 'deepcopy'

In [20]:
#copy() c1 nd c2 different  and view c1 changes reflect to c2

In [21]:
#c2=c1.view()

In [22]:
b.shape #for 1d 3 elements 

(3,)

In [23]:
z.shape # 3d 

(2, 2, 3)